version: '3.8'

services:
  cache:
    image: redis:alpine
    environment:
      - REDIS_HOST_PASSWORD
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass $$REDIS_HOST_PASSWORD
    volumes:
      - cache:/data

  app:
    image: ecency/vision:development
    environment:
      - USE_PRIVATE
      - REDIS_HOST_PASSWORD
      - REDIS_HOST=cache
    ports:
      - "3000:3000"
    depends_on:
      - cache
    deploy:
      replicas: 4
      resources:
        limits:
          cpus: "0.9"
          memory: 2048M
      update_config:
        parallelism: 4
        order: start-first
        failure_action: rollback
        delay: 10s
      rollback_config:
        parallelism: 0
        order: stop-first
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 5
        window: 30s

volumes:
  cache:
    driver: local