version: '3.7'

services:
  app:
    image: ecency/vision:development
    environment:
      - USE_PRIVATE
    ports:
      - "3000:3000"
    deploy:
      replicas: 4
      resources:
        limits:
          cpus: "0.9"
          memory: 2048M
      update_config:
        parallelism: 4
        order: start-first
        failure_action: rollback
        delay: 10s
      rollback_config:
        parallelism: 0
        order: stop-first
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 5
        window: 30s

  redis:
    image: redis
    container_name: ecency_redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"
    volumes:
      - $PWD/redis/redis-data:/var/lib/redis
      - $PWD/redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server