version: "3.7"

services:
  redis:
    image: redis:alpine
    environment:
      - REDIS_HOST_PASSWORD
    restart: always
    ports:
      - "6379:6379"
    networks:
      - default
    command:
      - /bin/sh
      - -c
      - redis-server --save 20 1 --loglevel warning --requirepass "$${REDIS_HOST_PASSWORD:?REDIS_HOST_PASSWORD variable is not set}"
    volumes:
      - redis:/data

  web1:
    image: ecency/vision:development
    environment:
      - USE_PRIVATE
      - REDIS_HOST_PASSWORD
    ports:
      - "3001:3000"
    networks:
      - default
    depends_on:
      - redis

  web2:
    image: ecency/vision:development
    environment:
      - USE_PRIVATE
      - REDIS_HOST_PASSWORD
    ports:
      - "3002:3000"
    networks:
      - default
    depends_on:
      - redis

  nginx:
    build: ./nginx
    ports:
    - '80:80'
    networks:
      - default
    depends_on:
    - web1
    - web2

volumes:
  redis:
    driver: local
