name: Master CI/CD
on:
  push:
    branches:
      - master
jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, lint and/or test
      run: |
        yarn
        cd src/desktop
        yarn
        cd ../../
        cp src/config.example.ts src/config.ts
        yarn test --runInBand --updateSnapshot
      env:
        CI: true

  deploy:
    needs: tests
    runs-on: ubuntu-latest
    steps:
    - name: SSH and deploy node app
      uses: appleboy/ssh-action@5711a203b3207eb1c6cebec6ac2152ab210ec3ae
      env:
        STAGING_PORT: ${{secrets.STAGING_PORT}}
      with:
        host: ${{ secrets.SSH_PRODUCTION_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRODUCTION_KEY }}
        port: ${{ secrets.SSH_PORT }}
        envs: STAGING_PORT
        script: |
          cd ~/vision-production
          git pull origin master
          docker build . -t vision -f Dockerfile --no-cache
          docker image tag vision localhost:5000/vision:latest
          docker push localhost:5000/vision:latest
          docker stack deploy -c docker-compose.yml vision
          docker system prune -f
